CREATE TABLE black_listed_token
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_blacklistedtoken PRIMARY KEY (id)
);

CREATE TABLE email_outbox
(
    id           BIGINT NOT NULL,
    sender       VARCHAR(255),
    recipient    VARCHAR(255),
    subject      VARCHAR(255),
    body         VARCHAR(255),
    email_status SMALLINT,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_email_outbox PRIMARY KEY (id)
);

CREATE TABLE org_admin
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email                 VARCHAR(255)                            NOT NULL,
    password              VARCHAR(255)                            NOT NULL,
    failed_login_attempts INTEGER                                 NOT NULL,
    lockout_time          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_org_admin PRIMARY KEY (id)
);

CREATE TABLE org_admin_profile
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    logo_url             VARCHAR(255),
    description          VARCHAR(255),
    industry             VARCHAR(255),
    website              VARCHAR(255),
    profile_completeness SMALLINT,
    CONSTRAINT pk_org_admin_profile PRIMARY KEY (id)
);

CREATE TABLE organisation
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    plan_limit SMALLINT,
    CONSTRAINT pk_organisation PRIMARY KEY (id)
);

CREATE TABLE verification_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_email  VARCHAR(255)                            NOT NULL,
    is_used     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_verification_token PRIMARY KEY (id)
);

ALTER TABLE black_listed_token
    ADD CONSTRAINT uc_blacklistedtoken_token UNIQUE (token);

ALTER TABLE org_admin
    ADD CONSTRAINT uc_org_admin_email UNIQUE (email);

ALTER TABLE verification_token
    ADD CONSTRAINT uc_verification_token_token UNIQUE (token);

ALTER TABLE organisation
    ADD CONSTRAINT FK_ORGANISATION_ON_ID FOREIGN KEY (id) REFERENCES org_admin (id);

ALTER TABLE org_admin_profile
    ADD CONSTRAINT FK_ORG_ADMIN_PROFILE_ON_ID FOREIGN KEY (id) REFERENCES org_admin (id);

ALTER TABLE org_admin_profile
    ADD CONSTRAINT FK_ORG_ADMIN_PROFILE_ON_IDToR9YH FOREIGN KEY (id) REFERENCES organisation (id);